<?php

/**
 * Wsdl file.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the BSD License.
 *
 * Copyright(c) 2005 by Marcus Nyeholt. All rights reserved.
 *
 * To contact the author write to {@link mailto:tanus@users.sourceforge.net Marcus Nyeholt}
 * This file is part of the PRADO framework from {@link http://www.xisc.com}
 *
 * @author Marcus Nyeholt		<tanus@users.sourceforge.net>
 * @author Wei Zhuo <weizhuo[at]gmail[dot]com>
 */

namespace Prado\Wsdl;

/**
 * Contains the dom object used to build up the wsdl. The
 * operations generated by the generator are stored in here until the getWsdl()
 * method is called which builds and returns the generated XML string.
 * @author 		Marcus Nyeholt		<tanus@users.sourceforge.net>
 * @author Wei Zhuo <weizhuo[at]gmail[dot]com>
 */
class Wsdl
{
	/**
	 * The name of the service, usually the class name.
	 * @var string
	 */
	private string $serviceName;

	/**
	 * The URI the service is found at. An empty URI falls back to the current
	 * request, without its query string.
	 * @var string
	 */
	private string $serviceUri;

	/**
	 * The complexType declarations, indexed by type name. An array type holds an
	 * empty string, because its element is derived from its name.
	 * @var \ArrayObject<string, array<int, array<string, mixed>>|string>
	 */
	private \ArrayObject $types;

	/**
	 * The SOAP operations of the service.
	 * @var WsdlOperation[]
	 */
	private array $operations = [];

	/**
	 * The generated wsdl document.
	 * @var ?string
	 */
	private ?string $wsdl = null;

	/**
	 * The definitions element the document is built into.
	 * @var ?\DOMElement
	 */
	private ?\DOMElement $definitions = null;

	/**
	 * The namespace the generated types and messages belong to.
	 * @var string
	 */
	private string $targetNamespace = '';

	/**
	 * The binding style. Only rpc is generated.
	 * @var string
	 */
	private string $bindingStyle = 'rpc';

	/**
	 * The transport the binding uses.
	 * @var string
	 */
	private string $bindingTransport = 'http://schemas.xmlsoap.org/soap/http';

	/**
	 * The character encoding declared by the document.
	 * @var string
	 */
	private string $_encoding = '';

	/**
	 * Maps the type names accepted in a doc comment to their XSD equivalent. The
	 * aliases match the ones WsdlGenerator::convertType() accepts.
	 * @var array<string, string>
	 */
	private static array $_primitiveTypes = [
		'string' => 'xsd:string',
		'str' => 'xsd:string',
		'int' => 'xsd:int',
		'integer' => 'xsd:int',
		'float' => 'xsd:float',
		'double' => 'xsd:float',
		'boolean' => 'xsd:boolean',
		'bool' => 'xsd:boolean',
		'date' => 'xsd:date',
		'time' => 'xsd:time',
		'dateTime' => 'xsd:dateTime',
		'mixed' => 'xsd:anyType',
		'object' => 'xsd:struct',
	];

	/**
	 * The production an encoding name follows in an XML declaration.
	 */
	private const ENCODING_PATTERN = '/^[A-Za-z][A-Za-z0-9._-]*$/';

	/**
	 * Creates a new wsdl document.
	 * @param string $name The name of the service
	 * @param string $serviceUri The URI of the service that handles this WSDL
	 * @param string $encoding The character encoding of the document
	 */
	public function __construct($name, $serviceUri = '', $encoding = '')
	{
		$this->_encoding = $encoding;
		$this->serviceName = $name;
		$protocol = (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] !== 'off')) ? 'https://' : 'http://';
		if ($serviceUri === '') {
			$serviceUri = $protocol . ($_SERVER['HTTP_HOST'] ?? '') . ($_SERVER['PHP_SELF'] ?? '');
		}
		$this->serviceUri = str_replace('&amp;', '&', $serviceUri);
		$this->types = new \ArrayObject();
		$this->targetNamespace = 'urn:' . $name . 'wsdl';
	}

	/**
	 * Builds the document and returns it.
	 * @return string The generated wsdl
	 */
	public function getWsdl()
	{
		$this->buildWsdl();
		return $this->wsdl;
	}

	/**
	 * Generates the WSDL file into the $this->wsdl variable
	 * @throws \InvalidArgumentException if the encoding is not an XML encoding name
	 * @throws \RuntimeException if the generated document does not parse
	 * @return void
	 */
	protected function buildWsdl()
	{
		$encoding = '';
		if ($this->_encoding !== '') {
			if (!preg_match(self::ENCODING_PATTERN, $this->_encoding)) {
				throw new \InvalidArgumentException('"' . $this->_encoding . '" is not an XML encoding name.');
			}
			$encoding = 'encoding="' . $this->_encoding . '"';
		}

		$name = self::escapeAttribute($this->serviceName);
		$targetNamespace = self::escapeAttribute($this->targetNamespace);

		$xml = '<?xml version="1.0" ' . $encoding . '?>
                 <definitions name="' . $name . '" targetNamespace="' . $targetNamespace . '"
                     xmlns="http://schemas.xmlsoap.org/wsdl/"
                     xmlns:tns="' . $targetNamespace . '"
                     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                     xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"></definitions>';

		$dom = new \DOMDocument();
		$this->loadOrFail($dom, $xml);
		$this->definitions = $dom->documentElement;

		$this->addTypes($dom);

		$this->addMessages($dom);
		$this->addPortTypes($dom);
		$this->addBindings($dom);
		$this->addService($dom);

		$this->wsdl = $dom->saveXML();

		// A namespace URI is serialized as it was given, so a service name
		// carrying a character a URI cannot hold reaches the caller as a document
		// that no longer parses. Escaping does not reach a namespace declaration.
		$this->loadOrFail(new \DOMDocument(), $this->wsdl);
	}

	/**
	 * Parses a document, and reports the service rather than the parser when it
	 * does not parse.
	 * @param \DOMDocument $dom The document to parse into
	 * @param string $xml The document to parse
	 * @throws \RuntimeException if the document does not parse
	 * @return void
	 * @since 1.2
	 */
	private function loadOrFail(\DOMDocument $dom, $xml)
	{
		if (!@$dom->loadXml($xml)) {
			throw new \RuntimeException('The wsdl of the "' . $this->serviceName . '" service does not parse. Its name is not usable in a document.');
		}
	}

	/**
	 * Adds complexType definitions to the document
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	public function addTypes(\DOMDocument $dom)
	{
		if (!count($this->types)) {
			return;
		}
		$types = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:types');
		$schema = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:schema');
		$schema->setAttribute('targetNamespace', $this->targetNamespace);
		foreach ($this->types as $type => $elements) {
			$complexType = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:complexType');
			$complexType->setAttribute('name', $type);
			if (substr($type, strlen($type) - 5, 5) == 'Array') {  // if it's an array
				$sequence = $dom->createElement("xsd:sequence");

				$singularType = substr($type, 0, strlen($type) - 5);
				$e = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:element');
				$e->setAttribute('name', $singularType);
				$e->setAttribute('type', $this->getArrayElementType($type));
				$e->setAttribute('minOccurs', '0');
				$e->setAttribute('maxOccurs', 'unbounded');
				$sequence->appendChild($e);
				$complexType->appendChild($sequence);
			} else {
				$all = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:all');
				foreach ($elements as $elem) {
					$e = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:element');
					$e->setAttribute('name', $elem['name']);
					$e->setAttribute('type', $elem['type']);
					if ($elem['minOc'] !== false) {
						$e->setAttribute('minOccurs', $elem['minOc']);
					}
					if ($elem['maxOc'] !== false) {
						$e->setAttribute('maxOccurs', $elem['maxOc']);
					}
					if ($elem['nil'] !== false) {
						$e->setAttribute('nillable', $elem['nil']);
					}
					$all->appendChild($e);
				}
				$complexType->appendChild($all);
			}
			$schema->appendChild($complexType);
			$types->appendChild($schema);
		}

		$this->definitions->appendChild($types);
	}

	/**
	 * Escapes a value for an XML attribute. The opening of the document is
	 * assembled as text, so a value carrying a markup character reaches the parser
	 * as markup unless it is escaped first. The replacement names no charset,
	 * because the document is not always UTF-8.
	 * @param string $value The value to escape
	 * @return string The escaped value
	 * @since 1.2
	 */
	private static function escapeAttribute($value)
	{
		return str_replace(
			['&', '<', '>', '"', "'"],
			['&amp;', '&lt;', '&gt;', '&quot;', '&apos;'],
			(string) $value
		);
	}

	/**
	 * Resolves the element type of an array complexType. A primitive element
	 * takes its XSD type, anything else is a complexType in the target namespace.
	 * @param string $type The name of the array complexType, ending in 'Array'
	 * @return string The qualified type of the array's element
	 * @since 1.2
	 */
	protected function getArrayElementType($type)
	{
		$elementType = substr($type, 0, strlen($type) - 5);
		return self::$_primitiveTypes[$elementType] ?? 'tns:' . $elementType;
	}

	/**
	 * Resolves the namespace prefix of an array complexType's element.
	 * @deprecated 1.2 use {@link getArrayElementType}, which resolves the whole type name
	 * @param string $type The name of the array complexType, ending in 'Array'
	 * @return string 'xsd:' for a primitive element type, otherwise 'tns:'
	 */
	protected function getArrayTypePrefix($type)
	{
		$elementType = substr($type, 0, strlen($type) - 5);
		return isset(self::$_primitiveTypes[$elementType]) ? 'xsd:' : 'tns:';
	}

	/**
	 * Add messages for the service
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addMessages(\DOMDocument $dom)
	{
		foreach ($this->operations as $operation) {
			$operation->setMessageElements($this->definitions, $dom);
		}
	}

	/**
	 * Add the port types for the service
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addPortTypes(\DOMDocument $dom)
	{
		$portType = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:portType');
		$portType->setAttribute('name', $this->serviceName . 'PortType');

		$this->definitions->appendChild($portType);
		foreach ($this->operations as $operation) {
			$portOperation = $operation->getPortOperation($dom);
			$portType->appendChild($portOperation);
		}
	}

	/**
	 * Add the bindings for the service
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addBindings(\DOMDocument $dom)
	{
		$binding = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:binding');
		$binding->setAttribute('name', $this->serviceName . 'Binding');
		$binding->setAttribute('type', 'tns:' . $this->serviceName . 'PortType');

		$soapBinding = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/soap/', 'soap:binding');
		$soapBinding->setAttribute('style', $this->bindingStyle);
		$soapBinding->setAttribute('transport', $this->bindingTransport);
		$binding->appendChild($soapBinding);

		$this->definitions->appendChild($binding);

		foreach ($this->operations as $operation) {
			$bindingOperation = $operation->getBindingOperation($dom, $this->targetNamespace, $this->bindingStyle);
			$binding->appendChild($bindingOperation);
		}
	}

	/**
	 * Add the service definition
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addService(\DOMDocument $dom)
	{
		$service = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:service');
		$service->setAttribute('name', $this->serviceName . 'Service');

		$port = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:port');
		$port->setAttribute('name', $this->serviceName . 'Port');
		$port->setAttribute('binding', 'tns:' . $this->serviceName . 'Binding');

		$soapAddress = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/soap/', 'soap:address');
		$soapAddress->setAttribute('location', $this->serviceUri);
		$port->appendChild($soapAddress);

		$service->appendChild($port);

		$this->definitions->appendChild($service);
	}

	/**
	 * Adds an operation to have port types and bindings output
	 * @param WsdlOperation $operation The operation to add
	 * @return void
	 */
	public function addOperation(WsdlOperation $operation)
	{
		$this->operations[] = $operation;
	}

	/**
	 * Adds complexTypes to the wsdl
	 * @param string $type Name of the type
	 * @param array<int, array<string, mixed>>|string $elements Elements of the type, each an
	 * associative array of name and type, or an empty string for an array type
	 * @return void
	 */
	public function addComplexType($type, $elements)
	{
		$this->types[$type] = $elements;
	}
}
