<?php

/**
 * Wsdl file.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the BSD License.
 *
 * Copyright(c) 2005 by Marcus Nyeholt. All rights reserved.
 *
 * To contact the author write to {@link mailto:tanus@users.sourceforge.net Marcus Nyeholt}
 * This file is part of the PRADO framework from {@link http://www.xisc.com}
 *
 * @author Marcus Nyeholt		<tanus@users.sourceforge.net>
 * @author Wei Zhuo <weizhuo[at]gmail[dot]com>
 */

namespace Prado\Wsdl;

/**
 * Contains the dom object used to build up the wsdl. The
 * operations generated by the generator are stored in here until the getWsdl()
 * method is called which builds and returns the generated XML string.
 * @author 		Marcus Nyeholt		<tanus@users.sourceforge.net>
 * @author Wei Zhuo <weizhuo[at]gmail[dot]com>
 */
class Wsdl
{
	/**
	 * The name of the service, usually the class name. It names the service when
	 * the document is refused; {@see $name} is what the document carries.
	 * @var string
	 */
	private string $serviceName;

	/**
	 * The name the document carries for the service, as {@see documentName()}
	 * maps it. It is written where an NCName or a URI is expected, which a
	 * namespaced class name is not.
	 * @var string
	 */
	private string $name;

	/**
	 * The URI the service is found at. An empty URI falls back to the current
	 * request, without its query string.
	 * @var string
	 */
	private string $serviceUri;

	/**
	 * The complexType declarations, indexed by type name. An array type holds an
	 * empty string, because its element is derived from its name.
	 * @var \ArrayObject<string, array<int, array<string, mixed>>|string>
	 */
	private \ArrayObject $types;

	/**
	 * The SOAP operations of the service.
	 * @var WsdlOperation[]
	 */
	private array $operations = [];

	/**
	 * The generated wsdl document.
	 * @var ?string
	 */
	private ?string $wsdl = null;

	/**
	 * The definitions element the document is built into.
	 * @var ?\DOMElement
	 */
	private ?\DOMElement $definitions = null;

	/**
	 * The namespace the generated types and messages belong to.
	 * @var string
	 */
	private string $targetNamespace = '';

	/**
	 * The binding style. Only rpc is generated.
	 * @var string
	 */
	private string $bindingStyle = self::STYLE_RPC;

	/**
	 * The transport the binding uses.
	 * @var string
	 */
	private string $bindingTransport = 'http://schemas.xmlsoap.org/soap/http';

	/**
	 * The character encoding declared by the document.
	 * @var string
	 */
	private string $_encoding = '';

	/**
	 * Maps the type names accepted in a doc comment to their XSD equivalent. The
	 * aliases match the ones WsdlGenerator::convertType() accepts.
	 * @var array<string, string>
	 */
	private static array $_primitiveTypes = [
		'string' => 'xsd:string',
		'str' => 'xsd:string',
		'int' => 'xsd:int',
		'integer' => 'xsd:int',
		'float' => 'xsd:float',
		'double' => 'xsd:float',
		'boolean' => 'xsd:boolean',
		'bool' => 'xsd:boolean',
		'date' => 'xsd:date',
		'time' => 'xsd:time',
		'dateTime' => 'xsd:dateTime',
		'mixed' => 'xsd:anyType',
		'object' => 'xsd:anyType',
	];

	/**
	 * The production an encoding name follows in an XML declaration.
	 */
	private const ENCODING_PATTERN = '/^[A-Za-z][A-Za-z0-9._-]*$/';

	/**
	 * Remote procedure call style with SOAP encoding, as WSDL 1.1 and SOAP 1.1
	 * define it. A message carries one part per parameter, typed. This is what the
	 * generator has always produced, and remains the default.
	 * @since 1.2
	 */
	public const STYLE_RPC = 'rpc';

	/**
	 * Document style with literal encoding, following the wrapped convention of
	 * WS-I Basic Profile 1.1, which prohibits SOAP encoding (R2706). A message
	 * carries one part naming a global element that wraps the parameters.
	 * @since 1.2
	 */
	public const STYLE_DOCUMENT = 'document';

	/**
	 * Creates a new wsdl document. The service name is usually the class name of
	 * the provider, and reaches the document as {@see documentName()} maps it.
	 * @param mixed $name The name of the service, a string, or a value coerced to
	 * one as interpolation coerced it before the properties carried types
	 * @param string $serviceUri The URI of the service that handles this WSDL
	 * @param mixed $encoding The character encoding of the document, coerced the
	 * same way
	 * @param string $style The binding style, {@see STYLE_RPC} or {@see STYLE_DOCUMENT}
	 * @throws \InvalidArgumentException if the style is neither
	 */
	public function __construct($name, $serviceUri = '', $encoding = '', $style = self::STYLE_RPC)
	{
		$this->setBindingStyle($style);
		// The properties carry types, and the document was assembled by
		// interpolation before they did. Coerce at the boundary, so a caller that
		// passed something other than a string still gets what it always got.
		$this->_encoding = (string) $encoding;
		$this->serviceName = (string) $name;
		$this->name = self::documentName($this->serviceName);
		$protocol = (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] !== 'off')) ? 'https://' : 'http://';
		if ($serviceUri === '') {
			$serviceUri = $protocol . ($_SERVER['HTTP_HOST'] ?? '') . ($_SERVER['PHP_SELF'] ?? '');
		}
		$this->serviceUri = str_replace('&amp;', '&', $serviceUri);
		$this->types = new \ArrayObject();
		$this->targetNamespace = 'urn:' . $this->name . 'wsdl';
	}

	/**
	 * Maps a class name to the name the document carries for it. The service
	 * name and each complexType name are written as NCNames and into the target
	 * namespace URN, and a namespace separator is valid in neither. Each
	 * separator becomes a dot, which both allow, and a leading one is dropped:
	 * App\Soap\Quote is written as App.Soap.Quote. The full name is kept, so two
	 * classes sharing a short name do not collide. A class name holds nothing
	 * else a URI or an NCName refuses, and a global class name is returned as it
	 * stands, so the document of a global class is unchanged. The generator maps
	 * a type name the same way, so every tns: reference resolves.
	 * @param string $className The class name, with or without a leading separator
	 * @return string The name as the document carries it
	 * @since 1.2
	 */
	public static function documentName($className)
	{
		return str_replace('\\', '.', ltrim((string) $className, '\\'));
	}

	/**
	 * Builds the document and returns it.
	 * @return string The generated wsdl
	 */
	public function getWsdl()
	{
		$this->buildWsdl();
		return $this->wsdl;
	}

	/**
	 * Returns the binding style of the document.
	 * @return string {@see STYLE_RPC} or {@see STYLE_DOCUMENT}
	 * @since 1.2
	 */
	public function getBindingStyle()
	{
		return $this->bindingStyle;
	}

	/**
	 * Sets the binding style of the document.
	 * @param string $value {@see STYLE_RPC} or {@see STYLE_DOCUMENT}
	 * @throws \InvalidArgumentException if the style is neither
	 * @return void
	 * @since 1.2
	 */
	public function setBindingStyle($value)
	{
		if ($value !== self::STYLE_RPC && $value !== self::STYLE_DOCUMENT) {
			throw new \InvalidArgumentException('"' . $value . '" is not a binding style.');
		}

		$this->bindingStyle = $value;
	}

	/**
	 * Tells whether the document follows the document and literal style.
	 * @return bool Whether the style is {@see STYLE_DOCUMENT}
	 * @since 1.2
	 */
	protected function isDocumentStyle()
	{
		return $this->bindingStyle === self::STYLE_DOCUMENT;
	}

	/**
	 * Generates the WSDL file into the $this->wsdl variable
	 * @throws \InvalidArgumentException if the encoding is not an XML encoding name
	 * @throws \RuntimeException if the generated document does not parse, or the
	 * parser objects to the target namespace
	 * @return void
	 */
	protected function buildWsdl()
	{
		$encoding = '';
		if ($this->_encoding !== '') {
			if (!preg_match(self::ENCODING_PATTERN, $this->_encoding)) {
				throw new \InvalidArgumentException('"' . $this->_encoding . '" is not an XML encoding name.');
			}
			$encoding = 'encoding="' . $this->_encoding . '"';
		}

		$name = self::escapeAttribute($this->name);
		$targetNamespace = self::escapeAttribute($this->targetNamespace);

		$xml = '<?xml version="1.0" ' . $encoding . '?>
                 <definitions name="' . $name . '" targetNamespace="' . $targetNamespace . '"
                     xmlns="http://schemas.xmlsoap.org/wsdl/"
                     xmlns:tns="' . $targetNamespace . '"
                     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                     xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"></definitions>';

		$dom = new \DOMDocument();
		$this->loadOrFail($dom, $xml);
		$this->definitions = $dom->documentElement;

		$this->addTypes($dom);

		$this->addMessages($dom);
		$this->addPortTypes($dom);
		$this->addBindings($dom);
		$this->addService($dom);

		$this->wsdl = $dom->saveXML();
	}

	/**
	 * Parses a document, and reports the service rather than the parser when the
	 * parser objects to it. A namespace URI that is not a URI loads with a
	 * warning, which is as fatal as a failure: an error handler such as PRADO's
	 * throws on it, and hiding it hands the caller a document no client accepts.
	 * The parser keeps its errors here rather than raising them, so nothing
	 * reaches the error handler, and a document it said anything about is
	 * refused, naming what it said. Escaping does not reach a namespace
	 * declaration, so this is the check that keeps such a document from the
	 * caller.
	 * @param \DOMDocument $dom The document to parse into
	 * @param string $xml The document to parse
	 * @throws \RuntimeException if the document does not parse, or the parser
	 * objects to it
	 * @return void
	 * @since 1.2
	 */
	private function loadOrFail(\DOMDocument $dom, $xml)
	{
		$previous = libxml_use_internal_errors(true);
		libxml_clear_errors();

		try {
			$loaded = $dom->loadXML($xml);
			$errors = libxml_get_errors();
		} finally {
			libxml_clear_errors();
			libxml_use_internal_errors($previous);
		}

		if (!$loaded || $errors !== []) {
			$reason = $errors === [] ? '.' : ': ' . trim($errors[0]->message);
			throw new \RuntimeException('The wsdl of the "' . $this->serviceName . '" service does not parse' . $reason);
		}
	}

	/**
	 * Adds complexType definitions to the document
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	public function addTypes(\DOMDocument $dom)
	{
		if (!count($this->types) && !$this->isDocumentStyle()) {
			return;
		}
		$types = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:types');
		$schema = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:schema');
		$schema->setAttribute('targetNamespace', $this->targetNamespace);
		if ($this->isDocumentStyle()) {
			$schema->setAttribute('elementFormDefault', 'qualified');
		}
		foreach ($this->types as $type => $elements) {
			$complexType = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:complexType');
			$complexType->setAttribute('name', $type);
			if (substr($type, strlen($type) - 5, 5) == 'Array') {  // if it's an array
				$sequence = $dom->createElement("xsd:sequence");

				$singularType = substr($type, 0, strlen($type) - 5);
				$e = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:element');
				$e->setAttribute('name', $singularType);
				$e->setAttribute('type', $this->getArrayElementType($type));
				$e->setAttribute('minOccurs', '0');
				$e->setAttribute('maxOccurs', 'unbounded');
				$sequence->appendChild($e);
				$complexType->appendChild($sequence);
			} else {
				$compositor = $this->needsSequence($elements) ? 'xsd:sequence' : 'xsd:all';
				$all = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', $compositor);
				foreach ($elements as $elem) {
					$e = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:element');
					$e->setAttribute('name', $elem['name']);
					$e->setAttribute('type', $elem['type']);
					if ($elem['minOc'] !== false) {
						$e->setAttribute('minOccurs', $elem['minOc']);
					}
					if ($elem['maxOc'] !== false) {
						$e->setAttribute('maxOccurs', $elem['maxOc']);
					}
					if ($elem['nil'] !== false) {
						$e->setAttribute('nillable', $elem['nil']);
					}
					$all->appendChild($e);
				}
				$complexType->appendChild($all);
			}
			$schema->appendChild($complexType);
		}

		if ($this->isDocumentStyle()) {
			$this->addMessageElements($dom, $schema);
		}

		$types->appendChild($schema);
		$this->definitions->appendChild($types);
	}

	/**
	 * Escapes a value for an XML attribute. The opening of the document is
	 * assembled as text, so a value carrying a markup character reaches the parser
	 * as markup unless it is escaped first. The replacement names no charset,
	 * because the document is not always UTF-8.
	 * @param string $value The value to escape
	 * @return string The escaped value
	 * @since 1.2
	 */
	private static function escapeAttribute($value)
	{
		return str_replace(
			['&', '<', '>', '"', "'"],
			['&amp;', '&lt;', '&gt;', '&quot;', '&apos;'],
			(string) $value
		);
	}

	/**
	 * Adds the global elements a document and literal message names. The wrapped
	 * convention gives the request the name of the operation and the response that
	 * name followed by Response, each wrapping the parts in a sequence.
	 * @param \DOMDocument $dom The document to add to
	 * @param \DOMElement $schema The schema the elements belong to
	 * @return void
	 * @since 1.2
	 */
	protected function addMessageElements(\DOMDocument $dom, \DOMElement $schema)
	{
		foreach ($this->operations as $operation) {
			$name = $operation->getName();
			$input = $operation->getInputMessage();
			$output = $operation->getOutputMessage();

			$schema->appendChild($this->createMessageElement($dom, $name, $input === null ? [] : $input->getParts()));
			$schema->appendChild($this->createMessageElement($dom, $name . 'Response', $output === null ? [] : $output->getParts()));
		}
	}

	/**
	 * Builds the global element that wraps the parts of one message.
	 * @param \DOMDocument $dom The document to create in
	 * @param string $name The name of the element
	 * @param array<int, array<string, string>> $parts The parts to wrap
	 * @return \DOMElement The element
	 * @since 1.2
	 */
	protected function createMessageElement(\DOMDocument $dom, $name, array $parts)
	{
		$element = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:element');
		$element->setAttribute('name', $name);

		$complexType = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:complexType');
		$sequence = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:sequence');

		foreach ($parts as $part) {
			if (empty($part['name']) || empty($part['type'])) {
				continue;
			}
			$child = $dom->createElementNS('http://www.w3.org/2001/XMLSchema', 'xsd:element');
			$child->setAttribute('name', $part['name']);
			$child->setAttribute('type', $part['type']);
			$sequence->appendChild($child);
		}

		$complexType->appendChild($sequence);
		$element->appendChild($complexType);
		return $element;
	}

	/**
	 * Tells whether a complexType has to hold its elements in a sequence. An
	 * xsd:all holds each element at most once, so an occurrence count above one
	 * is only valid in an xsd:sequence.
	 * @param array<int, array<string, mixed>>|string $elements The elements of the type
	 * @return bool Whether a sequence is required
	 * @since 1.2
	 */
	protected function needsSequence($elements)
	{
		foreach ((array) $elements as $element) {
			foreach (['minOc', 'maxOc'] as $key) {
				$count = $element[$key] ?? false;
				if ($count === 'unbounded' || (is_numeric($count) && (int) $count > 1)) {
					return true;
				}
			}
		}

		return false;
	}

	/**
	 * Resolves the element type of an array complexType. A primitive element
	 * takes its XSD type, anything else is a complexType in the target namespace.
	 * @param string $type The name of the array complexType, ending in 'Array'
	 * @return string The qualified type of the array's element
	 * @since 1.2
	 */
	protected function getArrayElementType($type)
	{
		$elementType = substr($type, 0, strlen($type) - 5);
		return self::$_primitiveTypes[$elementType] ?? 'tns:' . $elementType;
	}

	/**
	 * Resolves the namespace prefix of an array complexType's element.
	 * @deprecated 1.2 use {@link getArrayElementType}, which resolves the whole type name
	 * @param string $type The name of the array complexType, ending in 'Array'
	 * @return string 'xsd:' for a primitive element type, otherwise 'tns:'
	 */
	protected function getArrayTypePrefix($type)
	{
		$elementType = substr($type, 0, strlen($type) - 5);
		return isset(self::$_primitiveTypes[$elementType]) ? 'xsd:' : 'tns:';
	}

	/**
	 * Add messages for the service
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addMessages(\DOMDocument $dom)
	{
		foreach ($this->operations as $operation) {
			$operation->setBindingStyle($this->bindingStyle);
			$operation->setMessageElements($this->definitions, $dom);
		}
	}

	/**
	 * Add the port types for the service
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addPortTypes(\DOMDocument $dom)
	{
		$portType = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:portType');
		$portType->setAttribute('name', $this->name . 'PortType');

		$this->definitions->appendChild($portType);
		foreach ($this->operations as $operation) {
			$portOperation = $operation->getPortOperation($dom);
			$portType->appendChild($portOperation);
		}
	}

	/**
	 * Add the bindings for the service
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addBindings(\DOMDocument $dom)
	{
		$binding = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:binding');
		$binding->setAttribute('name', $this->name . 'Binding');
		$binding->setAttribute('type', 'tns:' . $this->name . 'PortType');

		$soapBinding = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/soap/', 'soap:binding');
		$soapBinding->setAttribute('style', $this->bindingStyle);
		$soapBinding->setAttribute('transport', $this->bindingTransport);
		$binding->appendChild($soapBinding);

		$this->definitions->appendChild($binding);

		foreach ($this->operations as $operation) {
			$bindingOperation = $operation->getBindingOperation($dom, $this->targetNamespace, $this->bindingStyle);
			$binding->appendChild($bindingOperation);
		}
	}

	/**
	 * Add the service definition
	 * @param \DOMDocument $dom The document to add to
	 * @return void
	 */
	protected function addService(\DOMDocument $dom)
	{
		$service = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:service');
		$service->setAttribute('name', $this->name . 'Service');

		$port = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/', 'wsdl:port');
		$port->setAttribute('name', $this->name . 'Port');
		$port->setAttribute('binding', 'tns:' . $this->name . 'Binding');

		$soapAddress = $dom->createElementNS('http://schemas.xmlsoap.org/wsdl/soap/', 'soap:address');
		$soapAddress->setAttribute('location', $this->serviceUri);
		$port->appendChild($soapAddress);

		$service->appendChild($port);

		$this->definitions->appendChild($service);
	}

	/**
	 * Adds an operation to have port types and bindings output
	 * @param WsdlOperation $operation The operation to add
	 * @return void
	 */
	public function addOperation(WsdlOperation $operation)
	{
		$this->operations[] = $operation;
	}

	/**
	 * Adds complexTypes to the wsdl
	 * @param string $type Name of the type, as the document carries it, which for
	 * a namespaced class is what {@see documentName()} returns
	 * @param array<int, array<string, mixed>>|string $elements Elements of the type, each an
	 * associative array of name and type, or an empty string for an array type
	 * @return void
	 */
	public function addComplexType($type, $elements)
	{
		$this->types[$type] = $elements;
	}
}
